version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  # Laravel Backend
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    # Remove port mapping since we're using Nginx
    # ports:
    #   - "8000:80"
    expose:
      - "80"  # Only expose internally
    depends_on:
      - mysql
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    networks:
      - laravel_network

  # React Frontend with Vite
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_vite_app
    restart: unless-stopped
    # Remove port mapping since we're using Nginx
    # ports:
    #   - "5173:5173"
    expose:
      - "5173"  # Only expose internally
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost/api  # Point to Nginx proxy
    depends_on:
      - laravel
    networks:
      - laravel_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Remove the sites volume if not needed
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - laravel
      - react
    networks:
      - laravel_network

  # Redis (for caching and sessions)
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    expose:
      - "6379"  # Only expose internally
    # Remove external port mapping
    # ports:
    #   - "6379:6379"
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge